server:
  port: 23334
spring:
  application:
    name: files
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      # readWrite权限
      username: beichen
      password: beichen
      host: 127.0.0.1
      port: 27017
      database: file


#file-local
file:
  path: /Users/hanpengyu/Documents