server:
  port: 23334
spring:
  application:
    name: files
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      # readWrite权限
      username: beichen
      password: beichen
      host: 127.0.0.1
      port: 27017
      database: file
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
        #beichen-dev
        namespace: fcb46db4-0c13-4f69-85d4-d23bacdffd7a
#file-local
file:
  path: /Users/hanpengyu/Documents
