server:
  port: 23335
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: FILE
        uri: lb://files
        predicates:
          - Path=/files/**
        filters:
          - StripPrefix=1
      - id: ARTICLES
        uri: lb://articles
        predicates:
          - Path=/articles/**
        filters:
          - StripPrefix=1
