server:
  port: 23335
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true
        #beichen-dev
        namespace: fcb46db4-0c13-4f69-85d4-d23bacdffd7a
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: FILE
        uri: lb://files
        predicates:
          - Path=/files/**
        filters:
          - StripPrefix=1
      - id: CONSUMER
        uri: lb://consumer
        predicates:
          - Path=/consumer/**
        filters:
          - StripPrefix=1
      - id: PROVIDER
        uri: lb://provider
        predicates:
          - Path=/provider/**
        filters:
          - StripPrefix=1