server:
  port: 23335
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true
        #beichen-dev
        namespace: fcb46db4-0c13-4f69-85d4-d23bacdffd7a
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      # 备注 uri 一定不能和predicates的Path一样，不然有问题
      - id: CONSUMER
        uri: lb://consumer-server
        predicates:
          - Path=/consumer/**
      - id: PROVIDER
        uri: lb://provider-server
        predicates:
          - Path=/provider/**
      - id: XXL-JOB
        uri: lb://xxl-job-admin-server
        predicates:
          - Path=/xxl-job-admin/**