server:
  port: 23333
spring:
  application:
    name: article
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
        enabled: true
        register: true
        instance-id: ${spring.application.name}:${server.port}
        service-name: ${spring.application.name}